version: "3.9"

services:
  compound-node1-worker:
    image: compound:latest
    container_name: compound-node1-worker
    depends_on: 
      - db
    volumes: 
      - ../config.audit-node1.yaml:/app/config/config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    restart: always
    ports:
      - "8010:80"
    entrypoint:
      - "./compound"
      - "worker"

  compound-node1-server:
    image: compound:latest
    container_name: compound-node1-server
    depends_on: 
      - db
    volumes: 
      - ../config.audit-node1.yaml:/app/config/config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    restart: always
    ports:
      - "8011:80"
    entrypoint:
      - "./compound"
      - "server"

  compound-node2-worker:
    image: compound:latest
    container_name: compound-node2-worker
    depends_on: 
      - db
    volumes: 
      - ../config.audit-node2.yaml:/app/config/config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    restart: always
    ports:
      - "8020:80"
    entrypoint:
      - "./compound"
      - "worker"

  compound-node2-server:
    image: compound:latest
    container_name: compound-node2-server
    depends_on: 
      - db
    volumes: 
      - ../config.audit-node2.yaml:/app/config/config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    restart: always
    ports:
      - "8021:80"
    entrypoint:
      - "./compound"
      - "server"

  compound-node3-worker:
    image: compound:latest
    container_name: compound-node3-worker
    depends_on: 
      - db
    volumes: 
      - ../config.audit-node3.yaml:/app/config/config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    restart: always
    ports:
      - "8030:80"
    entrypoint:
      - "./compound"
      - "worker"

  compound-node3-server:
    image: compound:latest
    container_name: compound-node3-server
    depends_on: 
      - db
    volumes: 
      - ../config.audit-node3.yaml:/app/config/config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    restart: always
    ports:
      - "8031:80"
    entrypoint:
      - "./compound"
      - "server"


  db:
    image: mysql:5.7
    restart: always
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=compound
      - MYSQL_USER=compound
      - MYSQL_PASSWORD=compound

volumes:
  data: