// Code generated by "stringer -type ActionType -trimprefix ActionType"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActionTypeDefault-0]
	_ = x[ActionTypeSupply-1]
	_ = x[ActionTypeBorrow-2]
	_ = x[ActionTypeRedeem-3]
	_ = x[ActionTypeRepay-4]
	_ = x[ActionTypeMint-5]
	_ = x[ActionTypePledge-6]
	_ = x[ActionTypeUnpledge-7]
	_ = x[ActionTypeLiquidate-8]
	_ = x[ActionTypeRedeemTransfer-9]
	_ = x[ActionTypeUnpledgeTransfer-10]
	_ = x[ActionTypeBorrowTransfer-11]
	_ = x[ActionTypeLiquidateTransfer-12]
	_ = x[ActionTypeRefundTransfer-13]
	_ = x[ActionTypeRepayRefundTransfer-14]
	_ = x[ActionTypeLiquidateRefundTransfer-15]
	_ = x[ActionTypeProposalUpsertMarket-16]
	_ = x[ActionTypeProposalUpdateMarket-17]
	_ = x[ActionTypeProposalWithdrawReserves-18]
	_ = x[ActionTypeProposalProvidePrice-19]
	_ = x[ActionTypeProposalVote-20]
	_ = x[ActionTypeProposalInjectCTokenForMint-21]
	_ = x[ActionTypeProposalUpdateMarketAdvance-22]
	_ = x[ActionTypeProposalTransfer-23]
	_ = x[ActionTypeProposalCloseMarket-24]
	_ = x[ActionTypeProposalOpenMarket-25]
	_ = x[ActionTypeUpdateMarket-30]
	_ = x[ActionTypeQuickPledge-31]
	_ = x[ActionTypeQuickBorrow-32]
	_ = x[ActionTypeQuickBorrowTransfer-33]
	_ = x[ActionTypeQuickRedeem-34]
	_ = x[ActionTypeQuickRedeemTransfer-35]
	_ = x[ActionTypeProposalAddOracleSigner-36]
	_ = x[ActionTypeProposalRemoveOracleSigner-37]
	_ = x[ActionTypeProposalSetProperty-38]
	_ = x[ActionTypeProposalMake-39]
	_ = x[ActionTypeProposalShout-40]
}

const (
	_ActionType_name_0 = "DefaultSupplyBorrowRedeemRepayMintPledgeUnpledgeLiquidateRedeemTransferUnpledgeTransferBorrowTransferLiquidateTransferRefundTransferRepayRefundTransferLiquidateRefundTransferProposalUpsertMarketProposalUpdateMarketProposalWithdrawReservesProposalProvidePriceProposalVoteProposalInjectCTokenForMintProposalUpdateMarketAdvanceProposalTransferProposalCloseMarketProposalOpenMarket"
	_ActionType_name_1 = "UpdateMarketQuickPledgeQuickBorrowQuickBorrowTransferQuickRedeemQuickRedeemTransferProposalAddOracleSignerProposalRemoveOracleSignerProposalSetPropertyProposalMakeProposalShout"
)

var (
	_ActionType_index_0 = [...]uint16{0, 7, 13, 19, 25, 30, 34, 40, 48, 57, 71, 87, 101, 118, 132, 151, 174, 194, 214, 238, 258, 270, 297, 324, 340, 359, 377}
	_ActionType_index_1 = [...]uint8{0, 12, 23, 34, 53, 64, 83, 106, 132, 151, 163, 176}
)

func (i ActionType) String() string {
	switch {
	case 0 <= i && i <= 25:
		return _ActionType_name_0[_ActionType_index_0[i]:_ActionType_index_0[i+1]]
	case 30 <= i && i <= 40:
		i -= 30
		return _ActionType_name_1[_ActionType_index_1[i]:_ActionType_index_1[i+1]]
	default:
		return "ActionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
