// Code generated by "stringer -type ActionType -trimprefix ActionType"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActionTypeSupply-1]
	_ = x[ActionTypeBorrow-2]
	_ = x[ActionTypeBorrowTransfer-3]
	_ = x[ActionTypeRedeem-4]
	_ = x[ActionTypeRedeemTransfer-5]
	_ = x[ActionTypeRepay-6]
	_ = x[ActionTypeMint-7]
	_ = x[ActionTypePledge-8]
	_ = x[ActionTypeUnpledge-9]
	_ = x[ActionTypeUnpledgeTransfer-10]
	_ = x[ActionTypeSeizeToken-11]
	_ = x[ActionTypeSeizeTokenTransfer-12]
	_ = x[ActionTypeRefund-13]
	_ = x[ActionTypeAddMarket-14]
	_ = x[ActionTypeUpdateMarket-15]
	_ = x[ActionTypeInjectMintToken-16]
	_ = x[ActionTypeProposalWithdraw-17]
	_ = x[ActionTypeProposalPrice-18]
}

const _ActionType_name = "SupplyBorrowBorrowTransferRedeemRedeemTransferRepayMintPledgeUnpledgeUnpledgeTransferSeizeTokenSeizeTokenTransferRefundAddMarketUpdateMarketInjectMintTokenProposalWithdrawProposalPrice"

var _ActionType_index = [...]uint8{0, 6, 12, 26, 32, 46, 51, 55, 61, 69, 85, 95, 113, 119, 128, 140, 155, 171, 184}

func (i ActionType) String() string {
	i -= 1
	if i < 0 || i >= ActionType(len(_ActionType_index)-1) {
		return "ActionType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ActionType_name[_ActionType_index[i]:_ActionType_index[i+1]]
}
